/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/common/BaseButton.vue')['default']
    BaseModal: typeof import('./src/components/common/BaseModal.vue')['default']
    ChatPanel: typeof import('./src/components/chat/ChatPanel.vue')['default']
    ErrorMessage: typeof import('./src/components/common/ErrorMessage.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    PlayerCard: typeof import('./src/components/game/PlayerCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpectatePlayerCard: typeof import('./src/components/game/SpectatePlayerCard.vue')['default']
  }
}
